#!/usr/bin/env bash
# redirecting to another page
sudo sed -i 's/server_name _;/a \\n    location \/redirect_me {\n        return 301 '"https://www.youtube.com/watch?v=QH2-TGUlwu4"';\n    }\n' /etc/nginx/sites-available/default
sudo service nginx restart