#!/usr/bin/env bash
# Not found page 404
apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '/server_name _;/a \\n    location \/redirect_me {\n        return 301 '"https://www.youtube.com/watch?v=QH2-TGUlwu4"';\n    }\n' /etc/nginx/sites-available/default
sudo service nginx restart
sudo touch /var/www/html/error-404.html
sudo echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/error-404.html
sudo sed -i '/http {/http {\n\terror_page 404 /error-404.html;' /etc/nginx/nginx.conf
sudo service nginx restart