#!/usr/bin/env bash
# Not found page 404
apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '/server_name _;/a \\n    location \/redirect_me {\n        return 301 '"https://www.youtube.com/watch?v=QH2-TGUlwu4"';\n    }\n' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
sudo sed -i '/server_name _;/a \\t\\terror_page 404 \/error-404.html;\\nlocation = /error_404.html {root /usr/share/nginx/html;internal;}' /etc/nginx/sites-available/default
sudo service nginx restart