#!/usr/bin/env bash
# configure web-02 to be identical to web-01 and add custom HTTP header
apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i '/server_name _;/a \\n    location \/redirect_me {\n        return 301 '"https://www.youtube.com/watch?v=QH2-TGUlwu4"';\n    }\n' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '24i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
sudo sed -i '60i\	add_header X-Served-By "$hostname";' /etc/nginx/sites-available/default
sudo service nginx restart