#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt-get update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend myfrontend
    bind *:80
    mode http
    default_backend mybackend

backend mybackend
    mode http
    balance roundrobin
    server web-01 54.209.215.54:80 check
    server web-02 54.237.40.45:80 check
EOL
sudo service haproxy restart