#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt update
sudo apt upgrade -y
sudo apt install -y haproxy
sudo tee -a /etc/haproxy/haproxy.cfg << END

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 384035-web-01 54.209.215.54:80 check
    server 384035-web-02 54.237.40.45:80 check
END
sudo service haproxy start