#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
trap stillAlive SIGTERM
stillAlive()
{
	echo 'I am invincible!!!'
}
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
