#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# It only displays: username, user id, Home directory path for the user.
file="/etc/passwd"
while read -r line; do
	echo "$line" | cut -d ":" -f 1,4,6
done < $file
