#!/usr/bin/env bash
# This script gives you information about the school file.
file="school"
if [ -e $file ]
then
	echo "school file exists"
	content=""
	if [ -f $file ]
	then
		content="$(cat $file)"
	fi
	if [ -f $file ] && [ -z "$content" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
