#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
echo "
server {
    listen 8080 default_server;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
nc -z 0 8080

